/* Generated by tools/generate_feature.py. Original modular art. */
#ifndef NEON_FEATURE_ASSETS_H
#define NEON_FEATURE_ASSETS_H
#include "assets.h"
#define FEATURE_VRAM_BASE 0x7E000UL
#define FEATURE_VRAM_SIZE 8192UL
#define FEATURE_ART_BYTES 7680UL
#define FEATURE_CURSOR_BASE 0x7FE00UL
#define FEATURE_CURSOR_RESERVED_BYTES 512UL
#define FEATURE_HULL_CORE_X 73
#define FEATURE_HULL_CORE_Y 24
#define FEATURE_ARM_LEFT_X (-20)
#define FEATURE_ARM_RIGHT_X 172
static const Sprite feature_hull = {0,4032,176,60};
static const Sprite feature_arm_left = {176,4032,24,60};
static const Sprite feature_arm_right = {200,4032,24,60};
static const Sprite feature_core[2] = {{224,4032,30,30},{224,4062,30,30}};
#endif
