"""Reproducible native SDCC/Pasmo ROM build. No emulator/BIOS binaries packaged."""
from pathlib import Path
import subprocess, os, re, json, hashlib, sys, shutil
ROOT=Path(__file__).resolve().parents[1]
os.chdir(ROOT)
build=ROOT/'work/build';build.mkdir(parents=True,exist_ok=True)
out=ROOT.parent/'outputs/msx1/v1.3';out.mkdir(parents=True,exist_ok=True)
STAGES=5
SCENES=6
GIANT_SCENE=5
BANK_BYTES=8192
bindir=Path(os.environ.get('SDCC_BIN',str(ROOT.parent/'work/toolchain/sdcc/bin')))
env=dict(os.environ);env['PATH']=str(bindir)+os.pathsep+env.get('PATH','')
sdcc=os.environ.get('SDCC',str(bindir/'sdcc.exe'))
pasmo=os.environ.get('PASMO',shutil.which('pasmo') or 'C:/Software/Pasmo/pasmo.exe')
def run(args):
    r=subprocess.run([str(a) for a in args],env=env,text=True,capture_output=True)
    if r.stdout.strip():print(r.stdout.strip())
    if r.stderr.strip():print(r.stderr.strip())
    if r.returncode:raise SystemExit(r.returncode)
if '--pack-only' not in sys.argv:
    run([sys.executable,'tools/generate_assets.py'])
world_stats=[]
for stage in range(SCENES):
    raw=(ROOT/'assets'/f'world-{stage}.bin').read_bytes();assert len(raw)==16384
    packets=[(ROOT/'assets'/f'phase-{stage}-{phase:02}.bin').read_bytes() for phase in range(16)]
    assert all(len(p)<=8192 for p in packets)
    world_stats.append({'stage':stage+1,'bytes':len(raw),'vram_bytes':16384,'phases':16,'pcg_packet_bytes':sum(map(len,packets)),'raw_sha256':hashlib.sha256(raw).hexdigest()})
# Whole packets remain inside a bank, preserving direct ROM-to-VRAM transfer.
title_bank=6+SCENES*2
packet_first_bank=title_bank+2
packet_data={(s,p):(ROOT/'assets'/f'phase-{s}-{p:02}.bin').read_bytes()
             for s in range(SCENES) for p in range(16)}
boss_codec=json.loads((ROOT/'assets/codec-manifest-5.json').read_text())
name_data={e['file']:(ROOT/'assets'/e['file']).read_bytes() for e in boss_codec['names']}
for name,data in name_data.items():
    assert len(data)==640
    packet_data[name]=data
bins=[];locations={}
for key,data in sorted(packet_data.items(),key=lambda item:(-len(item[1]),str(item[0]))):
    index=next((i for i,b in enumerate(bins) if len(b)+len(data)<=BANK_BYTES),len(bins))
    if index==len(bins):bins.append(bytearray())
    locations[key]=(packet_first_bank+index,len(bins[index]))
    bins[index].extend(data)
used=(packet_first_bank+len(bins))*BANK_BYTES
assert used<=524288,f'512KiB ROM capacity exceeded: {used}'
layout=['/* Generated by build.py; addresses refer to the 6000-7FFF window. */',
        '#ifndef NEON_WORLD_LAYOUT_H','#define NEON_WORLD_LAYOUT_H',
        f'#define WORLD_COUNT {SCENES}',f'#define TITLE_BANK {title_bank}',f'#define GIANT_SCENE {GIANT_SCENE}',
        'typedef struct { unsigned char bank; unsigned int address; } WorldPacket;',
        'static const unsigned char world_banks[WORLD_COUNT] = {'+','.join(str(6+s*2) for s in range(SCENES))+'};',
        'static const WorldPacket world_packets[WORLD_COUNT][16] = {']
for s in range(SCENES):
    layout.append('{'+','.join('{%d,0x%04X}'%(locations[s,p][0],0x6000+locations[s,p][1]) for p in range(16))+'},')
layout.append('};')
layout.append('static const WorldPacket giant_names[3][16] = {')
for state in range(1,4):
    row=[]
    for phase in range(16):
        e=next(e for e in boss_codec['names'] if e['state']==state and e['phase']==phase)
        bank,offset=locations[e['file']]
        row.append('{%d,0x%04X}'%(bank,0x6000+offset))
    layout.append('{'+','.join(row)+'},')
layout.extend(['};','#endif'])
(ROOT/'src/world_layout.h').write_text('\n'.join(layout)+'\n')
from pcg_boss_art import phase_metadata
motion=phase_metadata()
header=['/* Generated physical-pixel target positions for the PCG hull. */','#ifndef NEON_BOSS_LAYOUT_H','#define NEON_BOSS_LAYOUT_H','#define GIANT_SCENE 5','typedef struct { unsigned char lx,ly,rx,ry,cx,cy; } GiantTargets;','static const GiantTargets giant_motion[16] = {']
for m in motion:header.append('{'+','.join(str(v) for part in ('left','right','core') for v in m[part])+'},')
header.extend(['};','#endif'])
(ROOT/'src/boss_layout.h').write_text('\n'.join(header)+'\n')
(out/'giant-motion.json').write_text(json.dumps(motion,indent=2)+'\n')
flags=['-mz80','--std-sdcc11','--opt-code-speed','--no-std-crt0','--code-loc','0x8000','--data-loc','0xE000']
rels=[]
for name in ['game','hardware','sound','world_load']:
    rel=build/(name+'.rel');rels.append(rel)
    # Always compile the current descriptors, including when --pack-only
    # reuses already generated artwork.
    run([sdcc,*flags,'-I','src','-c','src/'+name+'.c','-o',rel])
run([sdcc,*flags,'-o',build/'game.ihx',*rels])
mem={}
for line in (build/'game.ihx').read_text().splitlines():
    if not line.startswith(':'):continue
    rec=bytes.fromhex(line[1:]);assert sum(rec)%256==0,'Intel HEX checksum'
    size=rec[0];addr=int.from_bytes(rec[1:3],'big');typ=rec[3]
    if typ==0:
        for n,b in enumerate(rec[4:4+size]):
            assert 0x8000<=addr+n<0xE000,f'ROM runtime overflow: {addr+n:04X}'
            mem[addr+n]=b
text=(build/'game.map').read_text()
symbols={m.group(2):int(m.group(1),16) for m in re.finditer(r'^\s*([0-9A-F]{8})\s+(_[\w]+)\s',text,re.M)}
assert '_main' in symbols
area=re.search(r'^_DATA\s+([0-9A-F]+)\s+([0-9A-F]+)',text,re.M)
assert area and int(area[1],16)+int(area[2],16)<=0xF100, 'Game data overlaps stack guard at F100'
runtime=bytearray([0xFF]*0x6000)
for a,b in mem.items():runtime[a-0x8000]=b
boot_src=(ROOT/'src/boot.asm').read_text().replace('ENTRY_POINT',str(symbols['_main']))
(build/'boot.asm').write_text(boot_src)
run([pasmo,'--bin',build/'boot.asm',build/'boot.bin'])
boot=(build/'boot.bin').read_bytes();assert len(boot)==8192
records=(ROOT/'assets/sprite-records.bin').read_bytes();assert len(records)<8192
patterns=(ROOT/'assets/sprite-patterns.bin').read_bytes();assert len(patterns)==2048
rom=bytearray([0xFF]*524288)
def bank_write(bank,data):
    assert bank*8192+len(data)<=len(rom)
    rom[bank*8192:bank*8192+len(data)]=data
bank_write(0,boot);bank_write(1,runtime);bank_write(4,records);bank_write(5,patterns)
for stage in range(SCENES):
    bank_write(6+stage*2,(ROOT/'assets'/f'world-{stage}.bin').read_bytes())
bank_write(title_bank,(ROOT/'assets/title.bin').read_bytes())
for index,data in enumerate(bins):bank_write(packet_first_bank+index,data)
for key,data in packet_data.items():
    bank,offset=locations[key];start=bank*BANK_BYTES+offset
    assert offset+len(data)<=BANK_BYTES and rom[start:start+len(data)]==data
target=out/'NEON_REVENANT-MSX1-v1.3.rom';target.write_bytes(rom)
(build/'symbols.json').write_text(json.dumps(symbols,indent=2))
manifest={'title':'NEON REVENANT - MSX1 PCG Drive: Dawn Leviathan','version':'1.3','file':target.name,'mapper':'ASCII8','rom_bytes':len(rom),'allocated_bytes':used,'free_bytes':len(rom)-used,'runtime_bytes':max(mem)-0x8000+1,'runtime_address':'8000-DFFF','data_end':hex(int(area[1],16)+int(area[2],16)),'ram_required_bytes':32768,'ram_address':'8000-FFFF in one RAM slot','sprite_bytes':len(patterns),'worlds':world_stats,'video':'TMS9918A SCREEN2 256x192, 16 streamed PCG phases, two name pages, fixed palette, resident mode1 MAG2 sprites','v9990_required':False,'sha256':hashlib.sha256(rom).hexdigest(),'entry':hex(symbols['_main']),
 'packing':{'strategy':'first-fit-decreasing whole PCG packets, no runtime decompression','title_bank':title_bank,'first_packet_bank':packet_first_bank,'packet_banks':len(bins),'payload_bytes':sum(map(len,packet_data.values())),
 'packets':[{'stage':s,'phase':p,'bank':locations[s,p][0],'offset':locations[s,p][1],'bytes':len(packet_data[s,p]),'sha256':hashlib.sha256(packet_data[s,p]).hexdigest()} for s in range(SCENES) for p in range(16)]}}
manifest['packing']['boss_names']=[dict(e,bank=locations[e['file']][0],offset=locations[e['file']][1]) for e in boss_codec['names']]
manifest['giant_boss']={'scene':5,'states':4,'phase_count':16,'codec_sha256':hashlib.sha256((ROOT/'assets/codec-manifest-5.json').read_bytes()).hexdigest(),'max_part_transfer_bytes':boss_codec['max_part_transfer_bytes']}
(out/'build-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps(manifest,indent=2))
