"""Pack the original sprites losslessly for the internal V9968 renderer."""
from pathlib import Path
import re


def generate(root):
    text = (root / 'src/assets.h').read_text()
    # These pre-rendered banners are unused; the game draws its current names.
    text = re.sub(r'static const Sprite (stageBanner|bossBanner)\[3\] = .*?;', '', text)
    rects = [tuple(map(int, m)) for m in re.findall(r'\{(\d+),(\d+),(\d+),(\d+)\}', text)]
    rects += [(0, 922, 256, 18), (0, 941, 256, 14)]
    original = (root / 'assets/vram.bin').read_bytes()
    result = bytearray(81920)
    skyline = [0] * 256
    locations = {}
    occupied = set()

    def pixel(x, y):
        b = original[(y - 512) * 128 + x // 2]
        return b & 15 if x & 1 else b >> 4

    def put(x, y, color):
        i = (y - 512) * 128 + x // 2
        result[i] = ((result[i] & 240) | color) if x & 1 else ((result[i] & 15) | (color << 4))

    for index, (x, y, w, h) in sorted(enumerate(rects), key=lambda t: (max(t[1][2], t[1][3]), t[1][3]), reverse=True):
        ny, nx = min((max(skyline[z:z + w]), z) for z in range(0, 257 - w, 2))
        skyline[nx:nx + w] = [ny + h] * w
        locations[index] = (nx, ny + 512, w, h)
        for yy in range(h):
            for xx in range(w):
                put(nx + xx, ny + 512 + yy, pixel(x + xx, y + yy))
                occupied.add((nx + xx, ny + 512 + yy))
    assert max(skyline) <= 320, 'Packed atlas overlaps background scratch'

    # Verify every referenced pixel, including transparent pixels, after packing.
    for index, (x, y, w, h) in enumerate(rects):
        nx, ny, _, _ = locations[index]
        for yy in range(h):
            for xx in range(w):
                b = result[(ny - 512 + yy) * 128 + (nx + xx) // 2]
                assert (b & 15 if (nx + xx) & 1 else b >> 4) == pixel(x + xx, y + yy)

    indices = iter(range(len(rects) - 2))
    text = re.sub(r'\{(\d+),(\d+),(\d+),(\d+)\}', lambda m: '{' + ','.join(map(str, locations[next(indices)])) + '}', text)
    text = re.sub(r'#define HUD_TOP_Y \d+', f'#define HUD_TOP_Y {locations[len(rects)-2][1]}', text)
    text = re.sub(r'#define HUD_BOTTOM_Y \d+', f'#define HUD_BOTTOM_Y {locations[len(rects)-1][1]}', text)
    text = text.replace('Generated by tools/generate_assets.py.', 'Losslessly packed by tools/pack_internal.py.')
    (root / 'src/assets-internal.h').write_text(text)

    colors = (root / 'src/palette.h').read_text()
    color_map = [int(v, 0) for v in re.search(r'color_map\[256\]\s*=\s*\{([^}]+)', colors)[1].split(',') if v.strip()]
    for x, y, w, h in [(232, 544, 21, 21), (232, 565, 7, 8)]:
        assert all((x + xx, y + yy) not in occupied for yy in range(h) for xx in range(w))
    for yy in range(21):
        for xx in range(21):
            on = (yy in (0, 20) and (xx <= 5 or xx >= 15)) or (xx in (0, 20) and (yy <= 5 or yy >= 15))
            put(232 + xx, 544 + yy, color_map[0xF3] if on else 0)
    for yy in range(8):
        for xx in range(7):
            color = 0x24
            if 2 <= xx < 5 and 1 <= yy < 7:
                color = 0x3C
            if xx == 3 and 3 <= yy < 6:
                color = 0xFF
            put(232 + xx, 565 + yy, color_map[color])
    (root / 'assets/vram-internal.bin').write_bytes(result)


if __name__ == '__main__':
    generate(Path(__file__).resolve().parents[1])
